name: .NET Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MAIN_PROJECT: Source/YoloV8/YoloV8.csproj
  DEMO_PROJECT: Source/YoloV8.Demo/YoloV8.Demo.csproj
  TEST_PROJECT: Source/YoloV8.Tests/YoloV8.Tests.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build YoloV8
        run: dotnet build ${{ env.MAIN_PROJECT }}

      - name: Build YoloV8.Demo
        run: dotnet build ${{ env.DEMO_PROJECT }}

      - name: Run Tests
        run: dotnet test ${{ env.TEST_PROJECT }}
